# Some default env vars.
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = XCURSOR_THEME,"Phinger Cursors"
env = XCURSOR_SIZE,24

$terminal = kitty
$fileManager = nautilus
$menu = wofi --show drun --normal window
$mainMod = SUPER

source = monitors.conf
source = variables.conf
source = rules.conf
source = binds.conf
source = inputs.conf
source = appearance.conf

exec-once = waybar
exec-once = hyprpaper
