{
  inputs,
  lib,
  config,
  pkgs,
  unstablePkgs,
  ...
}: {
  environment.systemPackages = [
    pkgs.atuin
    unstablePkgs.bat
    pkgs.bottom
    pkgs.delta
    pkgs.dust
    pkgs.duf
    pkgs.fastfetch
    pkgs.fd
    pkgs.fzf
    pkgs.gcc
    pkgs.gh
    pkgs.git
    pkgs.git-extras
    pkgs.git-filter-repo
    pkgs.git-lfs
    pkgs.glab
    pkgs.glow
    pkgs.gnupg
    pkgs.heh
    pkgs.hexyl
    pkgs.killall
    pkgs.libsecret
    pkgs.luaPackages.fennel
    pkgs.micro
    pkgs.netcat-gnu
    pkgs.nix-index
    pkgs.openssl
    pkgs.ouch
    pkgs.pass
    pkgs.passh
    pkgs.pkg-config
    pkgs.pueue
    pkgs.rbw
    pkgs.ripgrep
    pkgs.rm-improved
    pkgs.starship
    pkgs.tealdeer
    pkgs.tree-sitter
    pkgs.wget
    pkgs.wl-clipboard
    pkgs.wtype
    pkgs.xclip
    pkgs.xcp
    pkgs.zellij
    pkgs.zoxide
    unstablePkgs.binsider
    unstablePkgs.just
    unstablePkgs.neovim
    unstablePkgs.nushell
    unstablePkgs.onefetch
    unstablePkgs.serie
    unstablePkgs.yazi
  ];
}
