- Cloud & Files:
    - Nextcloud:
        icon: nextcloud.png
        href: https://nextcloud.bulba.space
        description: Cloud storage & productivity
        ping: https://nextcloud.bulba.space/
        server: podman
        container: nextcloud
        widget:
          type: nextcloud
          url: https://nextcloud.bulba.space
          username: "{{HOMEPAGE_VAR_NEXTCLOUD_USERNAME}}"
          password: "{{HOMEPAGE_VAR_NEXTCLOUD_PASSWORD}}"
    - Nextcloud Office:
        icon: collabora-online.png
        href: https://collabora.bulba.space
        description: Document collaboration engine
        ping: https://collabora.bulba.space/
        server: podman
        container: nextcloud-collabora
    - Vikunja:
        icon: vikunja.png
        href: https://vikunja.bulba.space
        description: Tasks & project management
        ping: https://vikunja.bulba.space/
        server: podman
        container: vikunja
        widget:
          type: vikunja
          url: https://vikunja.bulba.space
          key: "{{HOMEPAGE_VAR_VIKUNJA_TOKEN}}"
          version: 2


- Services:
    - Gitea:
        icon: gitea.png
        href: https://gitea.bulba.space
        description: Self-hosted Git service
        ping: https://gitea.bulba.space/
        server: podman
        container: gitea
        widget:
          type: gitea
          url: https://gitea.bulba.space
          key: "{{HOMEPAGE_VAR_GITEA_TOKEN}}"
    - FreshRSS:
        icon: freshrss.png
        href: https://freshrss.bulba.space
        description: RSS feed aggregator
        ping: https://freshrss.bulba.space/
        server: podman
        container: freshrss
        widget:
          type: freshrss
          url: https://freshrss.bulba.space
          username: "{{HOMEPAGE_VAR_FRESHRSS_USERNAME}}"
          password: "{{HOMEPAGE_VAR_FRESHRSS_PASSWORD}}"
    - Blog:
        icon: hugo.png
        href: https://blog.bulba.space
        description: Personal Blog & Notes
        siteMonitor: https://blog.bulba.space
        favicon: https://blog.bulba.space/favicon.ico

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: https://jellyfin.bulba.space
        description: Media streaming server
        ping: https://jellyfin.bulba.space
        server: podman
        container: jellyfin

- Infrastructure:
    - Caddy:
        icon: caddy.png
        href: https://bulba.space
        description: Reverse proxy
        ping: https://bulba.space/
        server: podman
        container: caddy
    - Cloudflared:
        icon: cloudflare.png
        href: https://dash.cloudflare.com
        description: Cloudflare Tunnel
        ping: https://dash.cloudflare.com/
        server: podman
        container: cloudflared
    - CV Website:
        icon: mdi-web
        href: https://bulba.space
        description: Personal Website
        ping: https://bulba.space/
    - CV API:
        icon: mdi-api
        href: https://bulba.space/api
        description: CV data API
        server: podman
        container: cv-api
    - Homepage:
        icon: homepage.png
        href: https://home.bulba.space
        description: This dashboard
        server: podman
        container: homepage
