title: "Homeserver"
favicon: "https://www.bulba.space/favicon.png"
theme: dark
hideVersion: true
color: slate
headerStyle: boxed
layout:
  Cloud & Files:
    style: row
    columns: 3
  Services:
    style: row
    columns: 3
  Media:
    style: row
    columns: 1
  Infrastructure:
    style: row
    columns: 4
