{
  inputs,
  lib,
  config,
  pkgs,
  unstablePkgs,
  ...
}: {
  environment.systemPackages = [
    pkgs.cargo
    pkgs.flatpak
    pkgs.greetd
    pkgs.grim
    pkgs.grub2_efi
    pkgs.nix-ld
    pkgs.nmap
    pkgs.nodejs-slim_latest
    pkgs.phinger-cursors
    pkgs.pinentry-gnome3
    pkgs.qmk
    pkgs.qmk-udev-rules
    pkgs.qmk_hid
    pkgs.regreet
    pkgs.seahorse
    pkgs.walker
    pkgs.wayland
    pkgs.wayland-utils
    pkgs.xfce.thunar
    pkgs.xfce.tumbler
    pkgs.xh
    unstablePkgs.ghostty
    unstablePkgs.hyprland
    unstablePkgs.hyprlock
    unstablePkgs.hyprpaper
    unstablePkgs.hyprpicker
    unstablePkgs.hyprshot
    unstablePkgs.kitty
    unstablePkgs.libnotify
    unstablePkgs.swaynotificationcenter
    unstablePkgs.waybar
  ];
}
