# include ./theme.conf

# font_family      Consolas ligaturized v2
# bold_font        Consolas ligaturized v2 Bold
# italic_font      Consolas ligaturized v2 Italic
# bold_italic_font Consolas ligaturized v2 BoldItalic

font_size        16.0
hide_window_decorations	yes
enabled_layouts Grid, Stack, Splits, Horizontal, Vertical, Fat, Tall

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
