{
  inputs,
  outputs,
  lib,
  config,
  pkgs,
  unstablePkgs,
  nixers,
  ...
}: let
in {
  home.packages = [
    pkgs.bitwarden-desktop
    pkgs.babashka
    pkgs.bat-extras.batman
    pkgs.bat-extras.batdiff
    pkgs.bat-extras.batgrep
    pkgs.bat-extras.prettybat
    pkgs.blueman
    pkgs.broot
    pkgs.clapper
    pkgs.cliphist
    pkgs.distrobox
    pkgs.dvc
    pkgs.feh
    pkgs.git-lfs
    pkgs.go
    pkgs.has
    pkgs.hyperfine
    pkgs.imagemagick
    pkgs.impala
    pkgs.jujutsu
    pkgs.kubectl
    pkgs.lnav
    pkgs.lynx
    pkgs.minikube
    unstablePkgs.mission-center
    pkgs.neovide
    pkgs.nix-output-monitor
    pkgs.nix-tree
    pkgs.nh
    pkgs.nodejs_24
    pkgs.nwg-look
    unstablePkgs.obsidian
    pkgs.onlyoffice-desktopeditors
    pkgs.pandoc
    pkgs.pavucontrol
    unstablePkgs.podman-compose
    unstablePkgs.podman-desktop
    unstablePkgs.podman-tui
    pkgs.popsicle
    nixers.python-env
    nixers.rbw-autofill
    unstablePkgs.ruff
    pkgs.sshs
    unstablePkgs.uv
    pkgs.vial
    nixers.vivaldi-wayland
    unstablePkgs.visidata
    pkgs.vivaldi-ffmpeg-codecs
    nixers.walker-obsidian-search
    pkgs.warpinator
    pkgs.xarchiver
    pkgs.yubikey-agent
    pkgs.yubikey-manager
    pkgs.zathura
    unstablePkgs.zeal
    unstablePkgs.zed-editor
    unstablePkgs.zotero
    nixers.zen-browser
    # theming
    pkgs.adwaita-icon-theme
    pkgs.gtk-engine-murrine
    pkgs.gtk_engines
    pkgs.hicolor-icon-theme
    pkgs.phinger-cursors
    pkgs.tokyonight-gtk-theme
    # Backend dev tools
    pkgs.lua54Packages.lua
    pkgs.luajitPackages.luarocks
    pkgs.steam-run
    pkgs.tree-sitter
    unstablePkgs.vimPlugins.mason-lspconfig-nvim
  ];
}
